version: "3"
services:
  db:
    image: postgres:10.6-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flagsmith
    container_name: flagsmith_postgres
  api:
    image: flagsmith/flagsmith-api:latest
    environment:
      DJANGO_ALLOWED_HOSTS: "*" # Change this in production
      DATABASE_URL: postgresql://postgres:password@db:5432/flagsmith
      DJANGO_DB_HOST: db
      DJANGO_DB_NAME: flagsmith
      DJANGO_DB_USER: postgres
      DJANGO_DB_PASSWORD: password
      DJANGO_DB_PORT: 5432
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:db
    container_name: flagsmith_api
  frontend:
    image: flagsmith/flagsmith-frontend:latest
    environment:
      # You might need to change the 2 host names below depending on your docker dns setup
      API_URL: http://localhost:8000/api/v1/ 
      ASSET_URL: http://locahost:8080/
    ports:
      - "8080:8080"
    links:
      - api:api
    container_name: flagsmith_frontend
